Controllers/CompanyController.cs
using ASPTest.BLL;
using ASPTest.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPTest.Controllers
{
    public class CompanyController : Controller
    {
        CompanyBLL bll = new CompanyBLL();
        // GET: Company
        [HttpGet]
        public ActionResult ViewAllCompany()
        {
            return View(bll.ViewAllCompany());
        }
        [HttpGet]
        public ActionResult Company(int id=0)
        {
            if (id != 0)
                return View(bll.EditCompany(id));
            else
            {
                Ent_Company com = new Ent_Company();
                com.EnterpriseList = bll.EnterpriseList();
                
                return View(com);
            }
               
        }
        [HttpPost]
        public ActionResult Company(Ent_Company com)
        {
            com.ModifiedBy = Session["UserName"].ToString();
            com.ModifiedByDate = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            if (com.Enterprise_ID == 0)
                bll.AddComapny(com);
            else
                bll.UpdateCompany(com);
            return RedirectToAction("ViewAllCompany");
           
        }
        [HttpGet]
        public ActionResult DeleteCompany(int id = 0)
        {
            bll.DeleteCompany(id);
            return RedirectToAction("ViewAllCompany");
        }
    }
}

Controllers/FacilityController.cs
using ASPTest.BLL;
using ASPTest.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPTest.Controllers
{
    public class FacilityController : Controller
    {
        // GET: Facility
       
        FacilityBLL bll = new FacilityBLL();
        
        [HttpGet]
        public ActionResult ViewAllFacility()
        {

            return View(bll.ViewAllFaclility());
        }
        [HttpGet]
        public ActionResult Facility(int id = 0)
        {
            if (id != 0)
                return View(bll.EditEnterprise(id));
            else
                return View();
        }
        [HttpPost]
        public ActionResult Facility(Ent_Facility Facility)
        {
            Facility.ModifiedBy = Session["UserName"].ToString();
            Facility.ModifiedByDate = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            if (Facility.Facility_ID == 0)
                bll.AddFaclility(Facility);
            else
                bll.UpdateFaclility(Facility);
            return RedirectToAction("ViewAllFacility");
        }
        [HttpGet]
        public ActionResult DeleteFacility(int id)
        {
            bll.DeleteFaclility(id);
            return RedirectToAction("ViewAllFacility");
        }

    }
}

Controllers/PayerController.cs
using ASPTest.BLL;
using ASPTest.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPTest.Controllers
{
    public class PayerController : Controller
    {
        // GET: Payer
        PayerBLL bll = new PayerBLL();
        [HttpGet]
        public ActionResult ViewAllPayer()
        {

            return View(bll.ViewAllPayer());
        }
        [HttpGet]
        public ActionResult Payer(int id = 0)
        {
            if (id != 0)
                return View(bll.EditPayer(id));
            else
                return View();
        }
        [HttpPost]
        public ActionResult Payer(Ent_Payer Payer)
        {
            Payer.ModifiedBy = Session["UserName"].ToString();
            Payer.ModifiedByDate = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            if (Payer.Payer_ID == 0)
                bll.AddPayer(Payer);
            else
                bll.UpdatePayer(Payer);
            return RedirectToAction("ViewAllPayer");
        }
        [HttpGet]
        public ActionResult DeletePayer(int id)
        {
            bll.DeletePayer(id);
            return RedirectToAction("ViewAllPayer");
        }
    }
}

Controllers/ProviderController.cs
using ASPTest.BLL;
using ASPTest.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASPTest.Controllers
{
    public class ProviderController : Controller
    {

        ProviderBLL bll = new ProviderBLL();
        // GET: Provider
        [HttpGet]
        public ActionResult ViewAllProvider()
        {

            return View(bll.ViewAllProvider());
        }
        [HttpGet]
        public ActionResult Provider(int id = 0)
        {
            if (id != 0)
                return View(bll.EditProvider(id));
            else
                return View();
        }
        [HttpPost]
        public ActionResult Provider(Ent_Provider Provider)
        {
            Provider.ModifiedBy = Session["UserName"].ToString();
            Provider.ModifiedByDate = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            if (Provider.Provider_ID == 0)
                bll.AddProvider(Provider);
            else
                bll.UpdateProvider(Provider);
            return RedirectToAction("ViewAllProvider");
        }
        [HttpGet]
        public ActionResult DeleteProvider(int id)
        {
            bll.DeleteProvider(id);
            return RedirectToAction("ViewAllProvider");
        }
    }
}

Views/Shared/_Layout.cshtml
@{
   
    if (Session["UserName"] == null)
    {
        Response.Redirect("~/Login/Login");
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/jquery")*@




    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>



    <style>
        .dropdown-submenu {
            position: relative;
        }

            .dropdown-submenu a::after {
                transform: rotate(-90deg);
                position: absolute;
                right: 6px;
                top: .8em;
            }

            .dropdown-submenu .dropdown-menu {
                top: 0;
                left: 100%;
                margin-left: .1rem;
                margin-right: .1rem;
            }

        .image {
            width: 90px;
            height: 40px;
        }
        .bodycontainer {
             width: 100%;
             padding-right: 40px;
             padding-left: 40px;
             margin-right: auto;
             margin-left: auto;
            }

        /*footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            height: 50px;
        }*/
    </style>
    <script>
        $(document).ready(function () {
            $(function () {
                $('.dropdown-menu a.dropdown-toggle').on('click', function (e) {
                    if (!$(this).next().hasClass('show')) {
                        $(this).parents('.dropdown-menu').first().find('.show').removeClass("show");
                    }
                    var $subMenu = $(this).next(".dropdown-menu");
                    $subMenu.toggleClass('show');


                    $(this).parents('li.nav-item.dropdown.show').on('hidden.bs.dropdown', function (e) {
                        $('.dropdown-submenu .show').removeClass("show");
                    });
                    return false;
                });
                $('.logout').on('click', function (e) {
                       $.ajax({
                                    type: "GET",
                                    url: "https://localhost:44366/Login/Logout",
                                     success: function (data) {
                                           
                                    },
                                    error: function (data) {
                                        alert("Error occured!!")
                                    }
                                });
                });
            });
        });
        function myFunction() {

        }

    </script>

</head>
<body >
    <div>
        <!--Navbar-->
      
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                 <img src="~/Images/AtomLogo.png" class="image" />
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                   
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Master 
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="@Url.Action("ViewAllEnterprise","Enterprise")">Enterprise</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("ViewAllCompany","Company")">Company </a></li>
                            <li><a class="dropdown-item" href="@Url.Action("ViewAllFacility","Facility")">Facility</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("ViewAllProvider","Provider")">Provider</a></li>
                            <li><a class="dropdown-item" href="@Url.Action("ViewAllPayer","Payer")">Insurance</a></li>

                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Credentialing
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="#">Provider Credentialing</a></li>
                            <li><a class="dropdown-item" href="#">Facility Credentialing</a></li>
                          

                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Reports
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="#">File Allocation Reports</a></li>
                            <li><a class="dropdown-item" href="#">Client Invoice Report</a></li>
                            <li><a class="dropdown-item" href="#">Task Aging Report</a></li>
                            <li><a class="dropdown-item" href="#">Production Report</a></li>
                            <li><a class="dropdown-item" href="#">Production Detail Report</a></li>
                            <li><a class="dropdown-item" href="#">Non Workable Report</a></li>

                        </ul>
                    </li>
                </ul>

                <form class="form-inline my-2 my-lg-0">
                    <button class="logout btn btn-outline-primary my-2 my-sm-0" type="submit">Logout</button>
                </form>
            </div>
        </nav>
        <!--/.Navbar-->
    </div>

    <div class="bodycontainer body-content" style="margin-top:10px;">
        @RenderBody()
       

    </div>
    <footer class="footer font-small blue">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
            © 2019 Copyright:
            <a href="https://mdbootstrap.com/education/bootstrap/"> Atom.com</a>
        </div>
        <!-- Copyright -->

    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>